# Generated by Django 5.0.6 on 2024-05-24 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxSystem', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Salary',
        ),
    ]
