# Generated by Django 5.0.6 on 2024-05-23 03:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxSystem', '0002_customuser_created_by_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
