# Generated by Django 5.0.6 on 2024-05-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxSystem', '0003_alter_customuser_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='monthly_salary',
            field=models.IntegerField(default=0),
        ),
    ]
