# Generated by Django 5.0.6 on 2024-05-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxSystem', '0007_taxrecords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxrecords',
            name='payment_date',
            field=models.DateTimeField(),
        ),
    ]
