# Generated by Django 5.0.6 on 2024-05-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxSystem', '0009_taxrecords_has_approved_taxrecords_has_audit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxrecords',
            name='has_audit',
        ),
        migrations.AddField(
            model_name='taxrecords',
            name='audit_status',
            field=models.IntegerField(default=0),
        ),
    ]
