# Generated by Django 5.0.6 on 2024-05-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxSystem', '0011_remove_taxrecords_has_approved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_key', models.CharField(max_length=128, unique=True)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
    ]
